# Generated by Django 5.2.1 on 2025-05-18 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_benefit_employee_room_schedule_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Contact number must be between 7 and 15 digits, optional leading +')]),
        ),
    ]
