# Generated by Django 5.2.1 on 2025-05-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_options_alter_employee_contact_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
