# Generated by Django 5.2.1 on 2025-05-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employee_first_name_alter_employee_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='schedule',
        ),
        migrations.AddField(
            model_name='room',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
