# Generated by Django 5.2.1 on 2025-06-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_employee_schedule_room_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='room',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
