# Generated by Django 5.2.1 on 2025-06-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_schedule_options_alter_room_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
    ]
